In [1]:
!date

vie ene 10 16:50:42 CET 2020


In [2]:
# Active system's automagic
%automagic on


Automagic is ON, % prefix IS NOT needed for line magics.


In [3]:
# Load work environment

In [4]:
import os
os.getcwd()

'/home/dsc/Repos/TFM_Categorize_providers_based_on_descriptions_of_the_drug_plans/03_Presentation'

In [5]:
#folder = '/home/dsc/Repos/TFM_Categorize_providers_based_on_descriptions_of_the_drug_plans/03_Presentation'
folder = os.getcwd()
!ls {folder}

01_Loading_and_preprocessing_original_data.ipynb
01_OUT_csv_original_data_transformed.csv
02_Draw_transformed_data.ipynb
03_Data_preparation_and_pipelines_of_naive_models.ipynb
04a_ROC_auc_SVC_svm_hyperparameters.ipynb
04_Automatic_hyperparameter_search.ipynb
04b_ROC_auc_LOGREG_SAG_hyperparameters.ipynb
04c_ROC_auc_LOGREG_SAGA_hyperparameters.ipynb
05_Apply_final_LOGREG_SAG_model.ipynb
06_Apply_final_ROC_auc_LOGREG_SAG_complete.ipynb


In [6]:
os.chdir(folder)
os.getcwd()

'/home/dsc/Repos/TFM_Categorize_providers_based_on_descriptions_of_the_drug_plans/03_Presentation'

In [7]:
# Load library for work and analitics data
import pandas as pd
import numpy as np

In [8]:
!ls -ltr ../03_Presentation/01_OUT_csv_original_data_transformed.csv

-rw-rw-r-- 1 dsc dsc 27565813 ene 10 15:18 ../03_Presentation/01_OUT_csv_original_data_transformed.csv


In [9]:
# Read from excel files complete with column names stipulated and transform them
# (1) Imports:
import os
import glob

In [10]:
# (2) File list:
path = os.chdir(os.getcwd() + '/..' + '/03_Presentation')
!pwd

/home/dsc/Repos/TFM_Categorize_providers_based_on_descriptions_of_the_drug_plans/03_Presentation


In [11]:
%%time
# (3) Upload cvsv file:
df_from_xlsx_total = pd.read_csv("01_OUT_csv_original_data_transformed.csv")

CPU times: user 491 ms, sys: 47.4 ms, total: 538 ms
Wall time: 481 ms


In [12]:
len(df_from_xlsx_total)

306183

In [13]:
df_from_xlsx_total.columns

Index(['ESTADO', 'CONDADO', 'ORGANIZACION', 'TIPO_PLAN_GENERICO_MEDICARE',
       'PRIMA_MENSUAL_CONSOLIDADA', 'MEDICAMS_ANUALES_DEDUCIBLES',
       'TIPO_BENEFICIO', 'COBERTURA_ADICIONAL_OFRECIDA', 'DETALLE_BENEFICIO',
       'DESEMBOLSO_MAXIMO', 'CLASIFICACION'],
      dtype='object')

In [14]:
# Data mapping

In [15]:
df_ratings_lab_ohe = df_from_xlsx_total.reset_index(drop=True).copy()

In [16]:
df_ratings_lab_ohe.head(1)

ESTADO  CONDADO      ORGANIZACION TIPO_PLAN_GENERICO_MEDICARE  \
0  Alabama  Autauga  UnitedHealthcare                         HMO   

   PRIMA_MENSUAL_CONSOLIDADA  MEDICAMS_ANUALES_DEDUCIBLES TIPO_BENEFICIO  \
0                        0.0                          0.0       Enhanced   

  COBERTURA_ADICIONAL_OFRECIDA DETALLE_BENEFICIO  DESEMBOLSO_MAXIMO  \
0              No Gap Coverage                EA             4450.0   

  CLASIFICACION  
0           2.5

In [17]:
df_ratings_lab_ohe.columns

Index(['ESTADO', 'CONDADO', 'ORGANIZACION', 'TIPO_PLAN_GENERICO_MEDICARE',
       'PRIMA_MENSUAL_CONSOLIDADA', 'MEDICAMS_ANUALES_DEDUCIBLES',
       'TIPO_BENEFICIO', 'COBERTURA_ADICIONAL_OFRECIDA', 'DETALLE_BENEFICIO',
       'DESEMBOLSO_MAXIMO', 'CLASIFICACION'],
      dtype='object')

In [18]:
df_ratings_lab_ohe.dtypes

ESTADO                           object
CONDADO                          object
ORGANIZACION                     object
TIPO_PLAN_GENERICO_MEDICARE      object
PRIMA_MENSUAL_CONSOLIDADA       float64
MEDICAMS_ANUALES_DEDUCIBLES     float64
TIPO_BENEFICIO                   object
COBERTURA_ADICIONAL_OFRECIDA     object
DETALLE_BENEFICIO                object
DESEMBOLSO_MAXIMO               float64
CLASIFICACION                    object
dtype: object

In [19]:
df_ratings_lab_ohe.head(3)

ESTADO  CONDADO                           ORGANIZACION  \
0  Alabama  Autauga                       UnitedHealthcare   
1  Alabama  Autauga  Blue Cross and Blue Shield of Alabama   
2  Alabama  Autauga  Blue Cross and Blue Shield of Alabama   

  TIPO_PLAN_GENERICO_MEDICARE  PRIMA_MENSUAL_CONSOLIDADA  \
0                         HMO                        0.0   
1                         PPO                       99.0   
2                         PPO                      199.0   

   MEDICAMS_ANUALES_DEDUCIBLES TIPO_BENEFICIO COBERTURA_ADICIONAL_OFRECIDA  \
0                          0.0       Enhanced              No Gap Coverage   
1                        130.0          Basic              No Gap Coverage   
2                          0.0       Enhanced              No Gap Coverage   

  DETALLE_BENEFICIO  DESEMBOLSO_MAXIMO CLASIFICACION  
0                EA             4450.0           2.5  
1                BA             3400.0           2.5  
2                EA             3400.0           2.5

In [20]:
# Check UNIQUE values
df_ratings_lab_ohe['CLASIFICACION'].unique()

array(['2.5', '3', 'NO_ASIGNADO', '3.5', '4', '4.5', '5', '2'],
      dtype=object)

In [21]:
# Check NULL values
df_ratings_lab_ohe.isnull().sum()

ESTADO                          0
CONDADO                         0
ORGANIZACION                    0
TIPO_PLAN_GENERICO_MEDICARE     0
PRIMA_MENSUAL_CONSOLIDADA       0
MEDICAMS_ANUALES_DEDUCIBLES     0
TIPO_BENEFICIO                  0
COBERTURA_ADICIONAL_OFRECIDA    0
DETALLE_BENEFICIO               0
DESEMBOLSO_MAXIMO               0
CLASIFICACION                   0
dtype: int64

In [22]:
# Check NaN values
df_ratings_lab_ohe.isna().sum()

ESTADO                          0
CONDADO                         0
ORGANIZACION                    0
TIPO_PLAN_GENERICO_MEDICARE     0
PRIMA_MENSUAL_CONSOLIDADA       0
MEDICAMS_ANUALES_DEDUCIBLES     0
TIPO_BENEFICIO                  0
COBERTURA_ADICIONAL_OFRECIDA    0
DETALLE_BENEFICIO               0
DESEMBOLSO_MAXIMO               0
CLASIFICACION                   0
dtype: int64

In [23]:
# Create sample for new dataframe with OneHotEncoder

In [24]:
df_ratings_lab_ohe_sample = df_ratings_lab_ohe.sample(n=10000, random_state=888).reset_index(drop=True)

In [25]:
df_ratings_lab_ohe_sample.columns

Index(['ESTADO', 'CONDADO', 'ORGANIZACION', 'TIPO_PLAN_GENERICO_MEDICARE',
       'PRIMA_MENSUAL_CONSOLIDADA', 'MEDICAMS_ANUALES_DEDUCIBLES',
       'TIPO_BENEFICIO', 'COBERTURA_ADICIONAL_OFRECIDA', 'DETALLE_BENEFICIO',
       'DESEMBOLSO_MAXIMO', 'CLASIFICACION'],
      dtype='object')

In [26]:
df_ratings_lab_ohe_sample.head(1)

ESTADO   CONDADO                       ORGANIZACION  \
0  Indiana  Harrison  Anthem Blue Cross and Blue Shield   

  TIPO_PLAN_GENERICO_MEDICARE  PRIMA_MENSUAL_CONSOLIDADA  \
0                         PPO                       64.0   

   MEDICAMS_ANUALES_DEDUCIBLES TIPO_BENEFICIO COBERTURA_ADICIONAL_OFRECIDA  \
0                         60.0       Enhanced                Many Generics   

  DETALLE_BENEFICIO  DESEMBOLSO_MAXIMO CLASIFICACION  
0                EA             3400.0             3

In [27]:
df_ratings_lab_ohe_sample.dtypes

ESTADO                           object
CONDADO                          object
ORGANIZACION                     object
TIPO_PLAN_GENERICO_MEDICARE      object
PRIMA_MENSUAL_CONSOLIDADA       float64
MEDICAMS_ANUALES_DEDUCIBLES     float64
TIPO_BENEFICIO                   object
COBERTURA_ADICIONAL_OFRECIDA     object
DETALLE_BENEFICIO                object
DESEMBOLSO_MAXIMO               float64
CLASIFICACION                    object
dtype: object

In [28]:
# Check NULL values
df_ratings_lab_ohe_sample.isnull().sum()

ESTADO                          0
CONDADO                         0
ORGANIZACION                    0
TIPO_PLAN_GENERICO_MEDICARE     0
PRIMA_MENSUAL_CONSOLIDADA       0
MEDICAMS_ANUALES_DEDUCIBLES     0
TIPO_BENEFICIO                  0
COBERTURA_ADICIONAL_OFRECIDA    0
DETALLE_BENEFICIO               0
DESEMBOLSO_MAXIMO               0
CLASIFICACION                   0
dtype: int64

In [29]:
df_ratings_lab_ohe_sample.count()

ESTADO                          10000
CONDADO                         10000
ORGANIZACION                    10000
TIPO_PLAN_GENERICO_MEDICARE     10000
PRIMA_MENSUAL_CONSOLIDADA       10000
MEDICAMS_ANUALES_DEDUCIBLES     10000
TIPO_BENEFICIO                  10000
COBERTURA_ADICIONAL_OFRECIDA    10000
DETALLE_BENEFICIO               10000
DESEMBOLSO_MAXIMO               10000
CLASIFICACION                   10000
dtype: int64

In [30]:
# Dont limit column display
import pandas as pd
from IPython.display import display

pd.options.display.max_columns = None
display(df_ratings_lab_ohe_sample.head(1))

ESTADO   CONDADO                       ORGANIZACION  \
0  Indiana  Harrison  Anthem Blue Cross and Blue Shield   

  TIPO_PLAN_GENERICO_MEDICARE  PRIMA_MENSUAL_CONSOLIDADA  \
0                         PPO                       64.0   

   MEDICAMS_ANUALES_DEDUCIBLES TIPO_BENEFICIO COBERTURA_ADICIONAL_OFRECIDA  \
0                         60.0       Enhanced                Many Generics   

  DETALLE_BENEFICIO  DESEMBOLSO_MAXIMO CLASIFICACION  
0                EA             3400.0             3

In [31]:
display(df_ratings_lab_ohe_sample.columns)

Index(['ESTADO', 'CONDADO', 'ORGANIZACION', 'TIPO_PLAN_GENERICO_MEDICARE',
       'PRIMA_MENSUAL_CONSOLIDADA', 'MEDICAMS_ANUALES_DEDUCIBLES',
       'TIPO_BENEFICIO', 'COBERTURA_ADICIONAL_OFRECIDA', 'DETALLE_BENEFICIO',
       'DESEMBOLSO_MAXIMO', 'CLASIFICACION'],
      dtype='object')

In [32]:
print(pd.options.display.max_columns)

None


In [33]:
print(pd.options.display.max_rows)

60


In [34]:
df_ratings_lab_ohe_sample[0:1]

ESTADO   CONDADO                       ORGANIZACION  \
0  Indiana  Harrison  Anthem Blue Cross and Blue Shield   

  TIPO_PLAN_GENERICO_MEDICARE  PRIMA_MENSUAL_CONSOLIDADA  \
0                         PPO                       64.0   

   MEDICAMS_ANUALES_DEDUCIBLES TIPO_BENEFICIO COBERTURA_ADICIONAL_OFRECIDA  \
0                         60.0       Enhanced                Many Generics   

  DETALLE_BENEFICIO  DESEMBOLSO_MAXIMO CLASIFICACION  
0                EA             3400.0             3

In [35]:
df_ratings_lab_ohe_sample.columns

Index(['ESTADO', 'CONDADO', 'ORGANIZACION', 'TIPO_PLAN_GENERICO_MEDICARE',
       'PRIMA_MENSUAL_CONSOLIDADA', 'MEDICAMS_ANUALES_DEDUCIBLES',
       'TIPO_BENEFICIO', 'COBERTURA_ADICIONAL_OFRECIDA', 'DETALLE_BENEFICIO',
       'DESEMBOLSO_MAXIMO', 'CLASIFICACION'],
      dtype='object')

In [36]:
df_ratings_lab_ohe_sample["ESTADO"] = df_ratings_lab_ohe_sample["ESTADO"].astype(np.str)
df_ratings_lab_ohe_sample["CONDADO"] = df_ratings_lab_ohe_sample["CONDADO"].astype(np.str)
df_ratings_lab_ohe_sample["ORGANIZACION"] = df_ratings_lab_ohe_sample["ORGANIZACION"].astype(np.str)
df_ratings_lab_ohe_sample["TIPO_PLAN_GENERICO_MEDICARE"] = df_ratings_lab_ohe_sample["TIPO_PLAN_GENERICO_MEDICARE"].astype(np.str)
df_ratings_lab_ohe_sample["PRIMA_MENSUAL_CONSOLIDADA"] = df_ratings_lab_ohe_sample["PRIMA_MENSUAL_CONSOLIDADA"].astype(np.float64)
df_ratings_lab_ohe_sample["MEDICAMS_ANUALES_DEDUCIBLES"] = df_ratings_lab_ohe_sample["MEDICAMS_ANUALES_DEDUCIBLES"].astype(np.float64)
df_ratings_lab_ohe_sample["TIPO_BENEFICIO"] = df_ratings_lab_ohe_sample["TIPO_BENEFICIO"].astype(np.str)
df_ratings_lab_ohe_sample["COBERTURA_ADICIONAL_OFRECIDA"] = df_ratings_lab_ohe_sample["COBERTURA_ADICIONAL_OFRECIDA"].astype(np.str)
df_ratings_lab_ohe_sample["DETALLE_BENEFICIO"] = df_ratings_lab_ohe_sample["DETALLE_BENEFICIO"].astype(np.str)
df_ratings_lab_ohe_sample["DESEMBOLSO_MAXIMO"] = df_ratings_lab_ohe_sample["DESEMBOLSO_MAXIMO"].astype(np.float64)
df_ratings_lab_ohe_sample["CLASIFICACION"] = df_ratings_lab_ohe_sample["CLASIFICACION"].astype(np.str)

# Data Preparation

In [37]:
df_ratings_lab_ohe_sample.dtypes

ESTADO                           object
CONDADO                          object
ORGANIZACION                     object
TIPO_PLAN_GENERICO_MEDICARE      object
PRIMA_MENSUAL_CONSOLIDADA       float64
MEDICAMS_ANUALES_DEDUCIBLES     float64
TIPO_BENEFICIO                   object
COBERTURA_ADICIONAL_OFRECIDA     object
DETALLE_BENEFICIO                object
DESEMBOLSO_MAXIMO               float64
CLASIFICACION                    object
dtype: object

In [38]:
df_ratings_lab_ohe_sample.head(3)

ESTADO   CONDADO                                  ORGANIZACION  \
0         Indiana  Harrison             Anthem Blue Cross and Blue Shield   
1  North Carolina  Scotland  Blue Cross and Blue Shield of North Carolina   
2        Kentucky  Harrison                      Humana Insurance Company   

  TIPO_PLAN_GENERICO_MEDICARE  PRIMA_MENSUAL_CONSOLIDADA  \
0                         PPO                       64.0   
1                         HMO                       16.4   
2                         PPO                       73.0   

   MEDICAMS_ANUALES_DEDUCIBLES TIPO_BENEFICIO COBERTURA_ADICIONAL_OFRECIDA  \
0                         60.0       Enhanced                Many Generics   
1                          0.0       Enhanced                Many Generics   
2                        360.0       Enhanced                          Yes   

  DETALLE_BENEFICIO  DESEMBOLSO_MAXIMO CLASIFICACION  
0                EA             3400.0             3  
1                EA             3400.0             4  
2                EA             6700.0             3

In [39]:
# Labeling through Label Encoding
from sklearn.preprocessing import LabelEncoder
lab = LabelEncoder() 

In [40]:
df_ratings_lab_ohe_sample.columns

Index(['ESTADO', 'CONDADO', 'ORGANIZACION', 'TIPO_PLAN_GENERICO_MEDICARE',
       'PRIMA_MENSUAL_CONSOLIDADA', 'MEDICAMS_ANUALES_DEDUCIBLES',
       'TIPO_BENEFICIO', 'COBERTURA_ADICIONAL_OFRECIDA', 'DETALLE_BENEFICIO',
       'DESEMBOLSO_MAXIMO', 'CLASIFICACION'],
      dtype='object')

In [41]:
df_ratings_lab_ohe_sample['ESTADO']= lab.fit_transform(df_ratings_lab_ohe_sample['ESTADO'])
df_ratings_lab_ohe_sample['CONDADO']= lab.fit_transform(df_ratings_lab_ohe_sample['CONDADO'])
df_ratings_lab_ohe_sample['ORGANIZACION']= lab.fit_transform(df_ratings_lab_ohe_sample['ORGANIZACION'])
#df_ratings_lab_ohe_sample['PLAN']= lab.fit_transform(df_ratings_lab_ohe_sample['PLAN'])
df_ratings_lab_ohe_sample['TIPO_PLAN_GENERICO_MEDICARE']= lab.fit_transform(df_ratings_lab_ohe_sample['TIPO_PLAN_GENERICO_MEDICARE'])
df_ratings_lab_ohe_sample['PRIMA_MENSUAL_CONSOLIDADA']= lab.fit_transform(df_ratings_lab_ohe_sample['PRIMA_MENSUAL_CONSOLIDADA'])
df_ratings_lab_ohe_sample['MEDICAMS_ANUALES_DEDUCIBLES']= lab.fit_transform(df_ratings_lab_ohe_sample['MEDICAMS_ANUALES_DEDUCIBLES'])
df_ratings_lab_ohe_sample['TIPO_BENEFICIO']= lab.fit_transform(df_ratings_lab_ohe_sample['TIPO_BENEFICIO'])
df_ratings_lab_ohe_sample['COBERTURA_ADICIONAL_OFRECIDA']= lab.fit_transform(df_ratings_lab_ohe_sample['COBERTURA_ADICIONAL_OFRECIDA'])
df_ratings_lab_ohe_sample['DETALLE_BENEFICIO']= lab.fit_transform(df_ratings_lab_ohe_sample['DETALLE_BENEFICIO'])
#df_ratings_lab_ohe_sample['CONTRATO_ID']= lab.fit_transform(df_ratings_lab_ohe_sample['CONTRATO_ID'])
#df_ratings_lab_ohe_sample['PLAN_ID']= lab.fit_transform(df_ratings_lab_ohe_sample['PLAN_ID'])
#df_ratings_lab_ohe_sample['SEGMENTO_ID']= lab.fit_transform(df_ratings_lab_ohe_sample['SEGMENTO_ID'])
df_ratings_lab_ohe_sample['DESEMBOLSO_MAXIMO']= lab.fit_transform(df_ratings_lab_ohe_sample['DESEMBOLSO_MAXIMO'])
#df_ratings_lab_ohe_sample['CLASIFICACION']= lab.fit_transform(df_ratings_lab_ohe_sample['CLASIFICACION'])

In [42]:
df_ratings_lab_ohe_sample.head(1)

ESTADO  CONDADO  ORGANIZACION  TIPO_PLAN_GENERICO_MEDICARE  \
0      12      671            35                            5   

   PRIMA_MENSUAL_CONSOLIDADA  MEDICAMS_ANUALES_DEDUCIBLES  TIPO_BENEFICIO  \
0                        192                           10               1   

   COBERTURA_ADICIONAL_OFRECIDA  DETALLE_BENEFICIO  DESEMBOLSO_MAXIMO  \
0                             8                  3                 37   

  CLASIFICACION  
0             3

In [43]:
# Load variables with sample data.
X = np.array(df_ratings_lab_ohe_sample.drop('CLASIFICACION', 1))
y = np.array(df_ratings_lab_ohe_sample["CLASIFICACION"])
X.shape

(10000, 10)

In [44]:
# normalization
X=(X-np.min(X))/(np.max(X)-np.min(X))

In [45]:
# Train-test split and load the library
from sklearn.model_selection import train_test_split
# Create 2 groups each with input and labels
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [46]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

In [47]:
df_ratings_lab_ohe_sample.columns

Index(['ESTADO', 'CONDADO', 'ORGANIZACION', 'TIPO_PLAN_GENERICO_MEDICARE',
       'PRIMA_MENSUAL_CONSOLIDADA', 'MEDICAMS_ANUALES_DEDUCIBLES',
       'TIPO_BENEFICIO', 'COBERTURA_ADICIONAL_OFRECIDA', 'DETALLE_BENEFICIO',
       'DESEMBOLSO_MAXIMO', 'CLASIFICACION'],
      dtype='object')

In [48]:
df_ratings_lab_ohe_sample.head(1)

ESTADO  CONDADO  ORGANIZACION  TIPO_PLAN_GENERICO_MEDICARE  \
0      12      671            35                            5   

   PRIMA_MENSUAL_CONSOLIDADA  MEDICAMS_ANUALES_DEDUCIBLES  TIPO_BENEFICIO  \
0                        192                           10               1   

   COBERTURA_ADICIONAL_OFRECIDA  DETALLE_BENEFICIO  DESEMBOLSO_MAXIMO  \
0                             8                  3                 37   

  CLASIFICACION  
0             3

In [49]:
df_ratings_lab_ohe_sample.shape

(10000, 11)

In [50]:
df_ratings_lab_ohe_sample.isnull().sum()

ESTADO                          0
CONDADO                         0
ORGANIZACION                    0
TIPO_PLAN_GENERICO_MEDICARE     0
PRIMA_MENSUAL_CONSOLIDADA       0
MEDICAMS_ANUALES_DEDUCIBLES     0
TIPO_BENEFICIO                  0
COBERTURA_ADICIONAL_OFRECIDA    0
DETALLE_BENEFICIO               0
DESEMBOLSO_MAXIMO               0
CLASIFICACION                   0
dtype: int64

In [51]:
# Create the encoder (by OneHotEncoder)
encoder = OneHotEncoder(handle_unknown='ignore')
# Assume for simplicity all features are categorical.
encoder.fit(X_train)

OneHotEncoder(categorical_features=None, categories=None, drop=None,
              dtype=<class 'numpy.float64'>, handle_unknown='ignore',
              n_values=None, sparse=True)

In [52]:
# Apply the encoder.
X_train = encoder.transform(X_train)
X_test = encoder.transform(X_test)

In [53]:
X.shape

(10000, 10)

In [54]:
X_train

<8000x2893 sparse matrix of type '<class 'numpy.float64'>'
	with 80000 stored elements in Compressed Sparse Row format>

In [55]:
X_test

<2000x2893 sparse matrix of type '<class 'numpy.float64'>'
	with 19847 stored elements in Compressed Sparse Row format>

In [56]:
#################

In [57]:
###############

#  Extracción de características , escala característica, reducción de dimensionalidad y prueba de flujos con estimador final adaptado

## Se utilizarán los hiperparámetros para:
#### Regresión Logisitica
#### Máquinas de vectores soporte
#### Árbol de decisión

## TAREAS:
#### Seguimiento con datos de prueba de puntuación
#### Comparar las exactitudes del modelo de pipeline
#### Identificar el “mejor” modelo, lo que significa que tiene la mayor precisión en nuestros datos de prueba
#### Persistir (guardar en archivo) todo el pipeline del “mejor” modelo

In [58]:
# import warnings filter
from warnings import simplefilter
# ignore all future warnings
simplefilter(action='ignore', category=FutureWarning)

# Load environment
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
#from sklearn.decomposition import PCA
from sklearn.pipeline import Pipeline
#from sklearn.externals import joblib
import joblib
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn import tree

from sklearn.decomposition import TruncatedSVD
from scipy.sparse import random as sparse_random
from sklearn.random_projection import sparse_random_matrix

from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

from sklearn import metrics
from sklearn.metrics import f1_score

In [59]:
# Construct some pipelines
# SCL: Feature Scaling
# PCA no admite entradas dispersas: ('pca', PCA(n_components=2)),
## SVD: Singular Value Decomposition (Dimensionality reduction)
pipe_lr = Pipeline([('scl', StandardScaler(with_mean=False)),
                    ('svd', TruncatedSVD(random_state=888)),
                    ('clf', LogisticRegression(random_state=888))])

pipe_kn = Pipeline([('scl', StandardScaler(with_mean=False)),
                     ('svd', TruncatedSVD(random_state=888)),
                     ('clf', KNeighborsClassifier())])

pipe_svm = Pipeline([('scl', StandardScaler(with_mean=False)),
                    ('svd', TruncatedSVD(random_state=888)),
                    ('clf', svm.SVC(random_state=888))])

pipe_dt = Pipeline([('scl', StandardScaler(with_mean=False)),
                    ('svd', TruncatedSVD(random_state=888)),
                    ('clf', tree.DecisionTreeClassifier(random_state=888))])

In [60]:
# List of pipelines for ease of iteration
pipelines = [pipe_lr, pipe_kn, pipe_svm, pipe_dt]

In [61]:
# Dictionary of pipelines and classifier types for ease of reference
pipe_dict = {0: 'Logistic Regression', 1: 'KNeighbors', 2: 'Support Vector Machine', 3: 'Decision Tree'}

In [62]:
# Fit the pipelines
for pipe in pipelines:
    pipe.fit(X_train, y_train)

In [63]:
# Compare ...
print('-----------------------------------------------------')
print('Pipeline test score model (on Train):')
for idx, val in enumerate(pipelines):
    print('\t%s: %.3f' % (pipe_dict[idx], val.score(X_train, y_train)))
print('-----------------------------------------------------')

-----------------------------------------------------
Pipeline test score model (on Train):
	Logistic Regression: 0.269
	KNeighbors: 0.469
	Support Vector Machine: 0.321
	Decision Tree: 0.630
-----------------------------------------------------


In [64]:
print('-----------------------------------------------------')
print('Cross validation accuracy score (on Train):')
for idx, val in enumerate(pipelines):
    print('\t%s: %s' % (pipe_dict[idx], cross_val_score(val.fit(X_train,y_train),X,y,scoring="accuracy", cv=3)))
print('-----------------------------------------------------')

-----------------------------------------------------
Cross validation accuracy score (on Train):
	Logistic Regression: [0.25037481 0.24835033 0.24407085]
	KNeighbors: [0.31124438 0.29784043 0.31672171]
	Support Vector Machine: [0.32083958 0.31283743 0.32152507]
	Decision Tree: [0.28605697 0.27984403 0.29900931]
-----------------------------------------------------


In [65]:
print('-----------------------------------------------------')
print('Metric accuracy score (on Test):')
for idx, val in enumerate(pipelines):
    print('\t%s: %.3f' % (pipe_dict[idx], accuracy_score(y_test,val.predict(X_test))))
print('-----------------------------------------------------')

-----------------------------------------------------
Metric accuracy score (on Test):
	Logistic Regression: 0.283
	KNeighbors: 0.302
	Support Vector Machine: 0.328
	Decision Tree: 0.287
-----------------------------------------------------


In [66]:
# SI EXISTIERAN OBSERVACIONES DE TRAIN EN TEST:
print('-----------------------------------------------------')
print('Prediction classification report (on Test):')
for idx, val in enumerate(pipelines):
    #metrics.f1_score(y_test, y_pred, average='weighted', labels=np.unique(y_pred))
    #print('\t%s: %s\n' % (pipe_dict[idx], classification_report(y_test,val.predict(X_test))))
    print('\t%s: %s\n' % (pipe_dict[idx], 
                          metrics.f1_score(y_test,val.predict(X_test), 
                                           average='weighted', 
                                           labels=np.unique(val.predict(X_test)))))
print('-----------------------------------------------------')    

-----------------------------------------------------
Prediction classification report (on Test):
	Logistic Regression: 0.37967926749424236

	KNeighbors: 0.2965564910041764

	Support Vector Machine: 0.2955044224375928

	Decision Tree: 0.2882827376213729

-----------------------------------------------------


In [67]:
# Identify the most accurate model on test data
best_acc = 0.0
best_clf = 0
best_pipe = ''
for idx, val in enumerate(pipelines):
    if val.score(X_test, y_test) > best_acc:
        best_acc = val.score(X_test, y_test)
        best_pipe = val
    best_clf = idx
print('Classifier with best accuracy: %s' % pipe_dict[best_clf])

Classifier with best accuracy: Decision Tree


In [68]:
# NO COMPUTE the f1 score using unique(y_pred)

# Some labels in y_test don't appear in y_pred
import warnings
warnings.filterwarnings('always')  # "error", "ignore", "always", "default", "module" or "once"

# Import the necessary modules
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report

# Create training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=888)

# Create the classifier: logreg
logreg = LogisticRegression(verbose=0, multi_class='auto')

# Fit the classifier to the training data
logreg.fit(X_train,y_train)

# Predict the labels of the test set: y_pred
y_pred = logreg.predict(X_test)

# Compute and print the confusion matrix and classification report
print(confusion_matrix(y_test, y_pred))

[[  0   0   0   5   0   0   0   0]
 [  0   0   0 107   6  43   0   0]
 [  0   0   0 230  41  20   0   0]
 [  0   0   0 397  80  67   0   0]
 [  0   0   0 313  77  80   0   0]
 [  0   0   0 170  33 141   0   0]
 [  0   0   0  25   2  17   0   0]
 [  0   0   0 105  24  17   0   0]]


/home/dsc/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [69]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           2       0.00      0.00      0.00         5
         2.5       0.00      0.00      0.00       156
           3       0.00      0.00      0.00       291
         3.5       0.29      0.73      0.42       544
           4       0.29      0.16      0.21       470
         4.5       0.37      0.41      0.39       344
           5       0.00      0.00      0.00        44
 NO_ASIGNADO       0.00      0.00      0.00       146

    accuracy                           0.31      2000
   macro avg       0.12      0.16      0.13      2000
weighted avg       0.21      0.31      0.23      2000



/home/dsc/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/dsc/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/dsc/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [70]:
!date

vie ene 10 16:51:18 CET 2020
