In [1]:
!date

vie ene 10 18:37:32 CET 2020


In [2]:
# Active system's automagic
%automagic on


Automagic is ON, % prefix IS NOT needed for line magics.


In [3]:
# Load work environment

In [4]:
import os
os.getcwd()

'/home/dsc/Repos/TFM_Categorize_providers_based_on_descriptions_of_the_drug_plans/03_Presentation'

In [5]:
#folder = '/home/dsc/Repos/TFM_Categorize_providers_based_on_descriptions_of_the_drug_plans/03_Presentation'
folder = os.getcwd()
!ls {folder}

01_Loading_and_preprocessing_original_data.ipynb
01_OUT_csv_original_data_transformed.csv
02_Sample_draw_transformed_data.ipynb
03_Sample_data_preparation_and_pipelines_of_naive_models.ipynb
04a_Sample_ROC_auc_SVC_svm_hyperparameters.ipynb
04b_Sample_ROC_auc_LOGREG_SAG_hyperparameters.ipynb
04c_Sample_ROC_auc_LOGREG_NEWTONcg_hyperparameters.ipynb
04_Sample_automatic_hyperparameter_search.ipynb
05_Apply_final_LOGREG_SAG_model.ipynb
06_Apply_final_ROC_auc_LOGREG_SAG_complete.ipynb


In [6]:
os.chdir(folder)
os.getcwd()

'/home/dsc/Repos/TFM_Categorize_providers_based_on_descriptions_of_the_drug_plans/03_Presentation'

In [7]:
# Load library for work and analitics data
import pandas as pd
import numpy as np

In [8]:
!ls -ltr ../03_Presentation/01_OUT_csv_original_data_transformed.csv

-rw-rw-r-- 1 dsc dsc 27565813 ene 10 15:18 ../03_Presentation/01_OUT_csv_original_data_transformed.csv


In [9]:
# Read from excel files complete with column names stipulated and transform them
# (1) Imports:
import os
import glob

In [10]:
# (2) File list:
path = os.chdir(os.getcwd() + '/..' + '/03_Presentation')
!pwd

/home/dsc/Repos/TFM_Categorize_providers_based_on_descriptions_of_the_drug_plans/03_Presentation


In [11]:
%%time
# (3) Upload cvsv file:
df_from_xlsx_total = pd.read_csv("01_OUT_csv_original_data_transformed.csv")

CPU times: user 509 ms, sys: 25.7 ms, total: 535 ms
Wall time: 473 ms


In [12]:
len(df_from_xlsx_total)

306183

In [13]:
df_from_xlsx_total.columns

Index(['ESTADO', 'CONDADO', 'ORGANIZACION', 'TIPO_PLAN_GENERICO_MEDICARE',
       'PRIMA_MENSUAL_CONSOLIDADA', 'MEDICAMS_ANUALES_DEDUCIBLES',
       'TIPO_BENEFICIO', 'COBERTURA_ADICIONAL_OFRECIDA', 'DETALLE_BENEFICIO',
       'DESEMBOLSO_MAXIMO', 'CLASIFICACION'],
      dtype='object')

In [14]:
# Data mapping

In [15]:
df_ratings_lab_ohe = df_from_xlsx_total.reset_index(drop=True).copy()

In [16]:
df_ratings_lab_ohe.head(1)

ESTADO  CONDADO      ORGANIZACION TIPO_PLAN_GENERICO_MEDICARE  \
0  Alabama  Autauga  UnitedHealthcare                         HMO   

   PRIMA_MENSUAL_CONSOLIDADA  MEDICAMS_ANUALES_DEDUCIBLES TIPO_BENEFICIO  \
0                        0.0                          0.0       Enhanced   

  COBERTURA_ADICIONAL_OFRECIDA DETALLE_BENEFICIO  DESEMBOLSO_MAXIMO  \
0              No Gap Coverage                EA             4450.0   

  CLASIFICACION  
0           2.5

In [17]:
df_ratings_lab_ohe.columns

Index(['ESTADO', 'CONDADO', 'ORGANIZACION', 'TIPO_PLAN_GENERICO_MEDICARE',
       'PRIMA_MENSUAL_CONSOLIDADA', 'MEDICAMS_ANUALES_DEDUCIBLES',
       'TIPO_BENEFICIO', 'COBERTURA_ADICIONAL_OFRECIDA', 'DETALLE_BENEFICIO',
       'DESEMBOLSO_MAXIMO', 'CLASIFICACION'],
      dtype='object')

In [18]:
df_ratings_lab_ohe.dtypes

ESTADO                           object
CONDADO                          object
ORGANIZACION                     object
TIPO_PLAN_GENERICO_MEDICARE      object
PRIMA_MENSUAL_CONSOLIDADA       float64
MEDICAMS_ANUALES_DEDUCIBLES     float64
TIPO_BENEFICIO                   object
COBERTURA_ADICIONAL_OFRECIDA     object
DETALLE_BENEFICIO                object
DESEMBOLSO_MAXIMO               float64
CLASIFICACION                    object
dtype: object

In [19]:
# Dont limit column display
import pandas as pd
from IPython.display import display

pd.options.display.max_columns = None
display(df_ratings_lab_ohe.head(1))

ESTADO  CONDADO      ORGANIZACION TIPO_PLAN_GENERICO_MEDICARE  \
0  Alabama  Autauga  UnitedHealthcare                         HMO   

   PRIMA_MENSUAL_CONSOLIDADA  MEDICAMS_ANUALES_DEDUCIBLES TIPO_BENEFICIO  \
0                        0.0                          0.0       Enhanced   

  COBERTURA_ADICIONAL_OFRECIDA DETALLE_BENEFICIO  DESEMBOLSO_MAXIMO  \
0              No Gap Coverage                EA             4450.0   

  CLASIFICACION  
0           2.5

In [20]:
# Check NULL values
df_ratings_lab_ohe.isnull().sum()

ESTADO                          0
CONDADO                         0
ORGANIZACION                    0
TIPO_PLAN_GENERICO_MEDICARE     0
PRIMA_MENSUAL_CONSOLIDADA       0
MEDICAMS_ANUALES_DEDUCIBLES     0
TIPO_BENEFICIO                  0
COBERTURA_ADICIONAL_OFRECIDA    0
DETALLE_BENEFICIO               0
DESEMBOLSO_MAXIMO               0
CLASIFICACION                   0
dtype: int64

In [21]:
# Check NaN values
df_ratings_lab_ohe.isna().sum()

ESTADO                          0
CONDADO                         0
ORGANIZACION                    0
TIPO_PLAN_GENERICO_MEDICARE     0
PRIMA_MENSUAL_CONSOLIDADA       0
MEDICAMS_ANUALES_DEDUCIBLES     0
TIPO_BENEFICIO                  0
COBERTURA_ADICIONAL_OFRECIDA    0
DETALLE_BENEFICIO               0
DESEMBOLSO_MAXIMO               0
CLASIFICACION                   0
dtype: int64

In [22]:
print(pd.options.display.max_columns)

None


In [23]:
print(pd.options.display.max_rows)

60


In [24]:
df_ratings_lab_ohe["ESTADO"] = df_ratings_lab_ohe["ESTADO"].astype(np.str)
df_ratings_lab_ohe["CONDADO"] = df_ratings_lab_ohe["CONDADO"].astype(np.str)
df_ratings_lab_ohe["ORGANIZACION"] = df_ratings_lab_ohe["ORGANIZACION"].astype(np.str)
df_ratings_lab_ohe["TIPO_PLAN_GENERICO_MEDICARE"] = df_ratings_lab_ohe["TIPO_PLAN_GENERICO_MEDICARE"].astype(np.str)
df_ratings_lab_ohe["PRIMA_MENSUAL_CONSOLIDADA"] = df_ratings_lab_ohe["PRIMA_MENSUAL_CONSOLIDADA"].astype(np.float64)
df_ratings_lab_ohe["MEDICAMS_ANUALES_DEDUCIBLES"] = df_ratings_lab_ohe["MEDICAMS_ANUALES_DEDUCIBLES"].astype(np.float64)
df_ratings_lab_ohe["TIPO_BENEFICIO"] = df_ratings_lab_ohe["TIPO_BENEFICIO"].astype(np.str)
df_ratings_lab_ohe["COBERTURA_ADICIONAL_OFRECIDA"] = df_ratings_lab_ohe["COBERTURA_ADICIONAL_OFRECIDA"].astype(np.str)
df_ratings_lab_ohe["DETALLE_BENEFICIO"] = df_ratings_lab_ohe["DETALLE_BENEFICIO"].astype(np.str)
df_ratings_lab_ohe["DESEMBOLSO_MAXIMO"] = df_ratings_lab_ohe["DESEMBOLSO_MAXIMO"].astype(np.float64)
df_ratings_lab_ohe["CLASIFICACION"] = df_ratings_lab_ohe["CLASIFICACION"].astype(np.str)

# Data Preparation

In [25]:
# Labeling through Label Encoding
from sklearn.preprocessing import LabelEncoder
lab = LabelEncoder() 

In [26]:
df_ratings_lab_ohe['ESTADO']= lab.fit_transform(df_ratings_lab_ohe['ESTADO'])
df_ratings_lab_ohe['CONDADO']= lab.fit_transform(df_ratings_lab_ohe['CONDADO'])
df_ratings_lab_ohe['ORGANIZACION']= lab.fit_transform(df_ratings_lab_ohe['ORGANIZACION'])
#df_ratings_lab_ohe['PLAN']= lab.fit_transform(df_ratings_lab_ohe['PLAN'])
df_ratings_lab_ohe['TIPO_PLAN_GENERICO_MEDICARE']= lab.fit_transform(df_ratings_lab_ohe['TIPO_PLAN_GENERICO_MEDICARE'])
df_ratings_lab_ohe['PRIMA_MENSUAL_CONSOLIDADA']= lab.fit_transform(df_ratings_lab_ohe['PRIMA_MENSUAL_CONSOLIDADA'])
df_ratings_lab_ohe['MEDICAMS_ANUALES_DEDUCIBLES']= lab.fit_transform(df_ratings_lab_ohe['MEDICAMS_ANUALES_DEDUCIBLES'])
df_ratings_lab_ohe['TIPO_BENEFICIO']= lab.fit_transform(df_ratings_lab_ohe['TIPO_BENEFICIO'])
df_ratings_lab_ohe['COBERTURA_ADICIONAL_OFRECIDA']= lab.fit_transform(df_ratings_lab_ohe['COBERTURA_ADICIONAL_OFRECIDA'])
df_ratings_lab_ohe['DETALLE_BENEFICIO']= lab.fit_transform(df_ratings_lab_ohe['DETALLE_BENEFICIO'])
#df_ratings_lab_ohe['CONTRATO_ID']= lab.fit_transform(df_ratings_lab_ohe['CONTRATO_ID'])
#df_ratings_lab_ohe['PLAN_ID']= lab.fit_transform(df_ratings_lab_ohe['PLAN_ID'])
#df_ratings_lab_ohe['SEGMENTO_ID']= lab.fit_transform(df_ratings_lab_ohe['SEGMENTO_ID'])
df_ratings_lab_ohe['DESEMBOLSO_MAXIMO']= lab.fit_transform(df_ratings_lab_ohe['DESEMBOLSO_MAXIMO'])
#df_ratings_lab_ohe['CLASIFICACION']= lab.fit_transform(df_ratings_lab_ohe['CLASIFICACION'])

In [27]:
df_ratings_lab_ohe.head(1)

ESTADO  CONDADO  ORGANIZACION  TIPO_PLAN_GENERICO_MEDICARE  \
0       0       86           476                            1   

   PRIMA_MENSUAL_CONSOLIDADA  MEDICAMS_ANUALES_DEDUCIBLES  TIPO_BENEFICIO  \
0                          0                            0               1   

   COBERTURA_ADICIONAL_OFRECIDA  DETALLE_BENEFICIO  DESEMBOLSO_MAXIMO  \
0                            19                  3                 81   

  CLASIFICACION  
0           2.5

In [28]:
# Load variables with sample data.
X = np.array(df_ratings_lab_ohe.drop('CLASIFICACION', 1))
y = np.array(df_ratings_lab_ohe["CLASIFICACION"])
X.shape

(306183, 10)

In [29]:
# normalization
#X=(X-np.min(X))/(np.max(X)-np.min(X))

In [30]:
# Train-test split and load the library
from sklearn.model_selection import train_test_split
# Create 2 groups each with input and labels
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=888)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [31]:
# Feature Scaling (normalization)
from sklearn.preprocessing import StandardScaler 
sc = StandardScaler() 
X_train = sc.fit_transform(X_train) 
X_test = sc.transform(X_test)

In [32]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

In [33]:
# Create the encoder (by OneHotEncoder)
encoder = OneHotEncoder(handle_unknown='ignore')
# Assume for simplicity all features are categorical.
encoder.fit(X_train)

OneHotEncoder(categorical_features=None, categories=None, drop=None,
              dtype=<class 'numpy.float64'>, handle_unknown='ignore',
              n_values=None, sparse=True)

In [34]:
# Apply the encoder.
X_train = encoder.transform(X_train)
X_test = encoder.transform(X_test)

In [35]:
X.shape

(306183, 10)

In [36]:
X_train

<244946x3810 sparse matrix of type '<class 'numpy.float64'>'
	with 2449460 stored elements in Compressed Sparse Row format>

In [37]:
X_test

<61237x3810 sparse matrix of type '<class 'numpy.float64'>'
	with 612362 stored elements in Compressed Sparse Row format>

In [38]:
#################

In [39]:
###############

In [40]:
# import warnings filter
from warnings import simplefilter
# ignore all future warnings
simplefilter(action='ignore', category=FutureWarning)

In [41]:
###################

## Logistic regression model with SKLearn

In [42]:
# Import the necessary modules
from sklearn import linear_model
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model.sag import sag_solver
from sklearn.metrics import confusion_matrix, classification_report
# Create teh Regression Logistic model and we make it fit (ajuste) to our set of inputs X and outputs "y".
model_LOGREG = linear_model.LogisticRegression(class_weight='balanced', multi_class='multinomial', solver='newton-cg', verbose=0, penalty='l2', max_iter=10000)
model_LOGREG.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight='balanced', dual=False,
                   fit_intercept=True, intercept_scaling=1, l1_ratio=None,
                   max_iter=10000, multi_class='multinomial', n_jobs=None,
                   penalty='l2', random_state=None, solver='newton-cg',
                   tol=0.0001, verbose=0, warm_start=False)

In [43]:
#Y confirmamos cuan bueno fue nuestro modelo utilizando model.score() que nos devuelve
#la precisión media de las predicciones, en nuestro caso del 59%
model_LOGREG.score(X_train, y_train)

0.7459317563871221

In [44]:
from sklearn import metrics

In [45]:
metrics.accuracy_score(y_train, model_LOGREG.predict(X_train))

0.7459317563871221

In [46]:
metrics.accuracy_score(y_test, model_LOGREG.predict(X_test))

0.7286444469846661

In [47]:
# We classify our entire set of X inputs using the "predict (X)" method for the model
# and we review some of its outputs to see if it matches the actual outputs of our origin
predictions_LOGREG = model_LOGREG.predict(X_test)

In [48]:
# Compute and print the confusion matrix and classification report
print(confusion_matrix(y_test, predictions_LOGREG))
print(classification_report(y_test, predictions_LOGREG))

[[  122    15     0     0     0     0     0     0]
 [   85  4150   241    24     1     3     0    93]
 [   65   743  6234  1309   293    74    16   462]
 [    3    85  2009 10570  2100   516    59   411]
 [    1    35   720  2366  9474  1588    83   330]
 [    1     3   146   375  1228  8788   331   148]
 [    0     0     0     4     2    21  1441     0]
 [   20    67   281    72   111    65    12  3841]]
              precision    recall  f1-score   support

           2       0.41      0.89      0.56       137
         2.5       0.81      0.90      0.86      4597
           3       0.65      0.68      0.66      9196
         3.5       0.72      0.67      0.69     15753
           4       0.72      0.65      0.68     14597
         4.5       0.79      0.80      0.80     11020
           5       0.74      0.98      0.85      1468
 NO_ASIGNADO       0.73      0.86      0.79      4469

    accuracy                           0.73     61237
   macro avg       0.70      0.80      0.74     6

In [49]:
# Check prediction classifier

In [50]:
print(predictions_LOGREG[7])

4


In [51]:
df_ratings_lab_ohe["CLASIFICACION"][7]

'NO_ASIGNADO'

In [52]:
print(predictions_LOGREG[0:7])

['4.5' '4.5' '4' '4' '3' '4' '2.5']


In [53]:
type(predictions_LOGREG)

numpy.ndarray

In [54]:
predictions_LOGREG.dtype

dtype('O')

In [55]:
predictions_LOGREG.shape

(61237,)

In [56]:
# Check model efficiency 

In [57]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, predictions_LOGREG))

0.7286444469846661


In [58]:
# The Quality of our model, gives us the average accuracy of the predictions
model_LOGREG.score(X_test,y_test)

0.7286444469846661

########################################################

##########################################

############################

## VALIDATE MODEL

In [59]:
df_ratings_lab_ohe.columns

Index(['ESTADO', 'CONDADO', 'ORGANIZACION', 'TIPO_PLAN_GENERICO_MEDICARE',
       'PRIMA_MENSUAL_CONSOLIDADA', 'MEDICAMS_ANUALES_DEDUCIBLES',
       'TIPO_BENEFICIO', 'COBERTURA_ADICIONAL_OFRECIDA', 'DETALLE_BENEFICIO',
       'DESEMBOLSO_MAXIMO', 'CLASIFICACION'],
      dtype='object')

In [60]:
df_ratings_lab_ohe.dtypes

ESTADO                           int64
CONDADO                          int64
ORGANIZACION                     int64
TIPO_PLAN_GENERICO_MEDICARE      int64
PRIMA_MENSUAL_CONSOLIDADA        int64
MEDICAMS_ANUALES_DEDUCIBLES      int64
TIPO_BENEFICIO                   int64
COBERTURA_ADICIONAL_OFRECIDA     int64
DETALLE_BENEFICIO                int64
DESEMBOLSO_MAXIMO                int64
CLASIFICACION                   object
dtype: object

In [61]:
df_ratings_lab_ohe.head(1)

ESTADO  CONDADO  ORGANIZACION  TIPO_PLAN_GENERICO_MEDICARE  \
0       0       86           476                            1   

   PRIMA_MENSUAL_CONSOLIDADA  MEDICAMS_ANUALES_DEDUCIBLES  TIPO_BENEFICIO  \
0                          0                            0               1   

   COBERTURA_ADICIONAL_OFRECIDA  DETALLE_BENEFICIO  DESEMBOLSO_MAXIMO  \
0                            19                  3                 81   

  CLASIFICACION  
0           2.5

In [ ]:
# We recompile our Logistic Regression model, at 80% of the input data in 10 partitions 
# and we calculate the new scoring by cross validation
from sklearn import model_selection
name='Logistic Regression'
kfold = model_selection.KFold(n_splits=10)
cv_results = model_selection.cross_val_score(model_LOGREG, X_train, y_train, cv=kfold, \
                                             scoring='accuracy', error_score=np.nan, verbose=0)
msg = "%s: %f (%f)" % (name, cv_results.mean(), cv_results.std())
print(msg)

In [ ]:
# And now we make the predictions (really classification) using our "cross validation set"
# that is to say of the subset that we had separated.
# Successes: xxx%
predictions_LOGREG = model_LOGREG.predict(X_test)
print(accuracy_score(y_test, predictions_LOGREG))

# Model results

In [ ]:
## Matrix of confusion for errors
print(confusion_matrix(y_test, predictions_LOGREG))

In [ ]:
## Classification report with our TEST set
# We observe the average F1-score
print(classification_report(y_test, predictions_LOGREG))

In [ ]:
aqui

# Classification (or prediction) of new values

In [ ]:
df_ratings_lab_ohe.columns

In [ ]:
df_ratings_lab_ohe.head(1)

In [ ]:
df_ratings_lab_ohe_sample.head(1)

In [ ]:
# Test and others parameters:
# a.- predict: just gives you the class for every example
# b.- predict_proba: gives you the probability for every class, and predict is just taking the class 
#     which maximal probability
# c.- predict_log_proba: gives you the logarithm of the probabilities, this is often handier as probabilities 
#     can become very, very small shareimprove this answer
# d.- coef_
# e.- score
# f.- decision function

In [ ]:
model_LOGREG.predict(X_test)

In [ ]:
model_LOGREG.predict_proba(X_test)

In [ ]:
model_LOGREG.predict_log_proba(X_test)

In [ ]:
model_LOGREG.coef_

In [ ]:
model_LOGREG.score

In [ ]:
df_ratings_lab_ohe.dtypes

In [ ]:
predictions_LOGREG[7]

In [ ]:
y_test[7]

In [ ]:
model_LOGREG.predict_proba(X_test)[7:8,]

In [ ]:
model_LOGREG.decision_function(X_test)

In [ ]:
model_LOGREG.classes_

In [ ]:
pd.DataFrame(model_LOGREG.predict_proba(X_test[7]), columns=model_LOGREG.classes_)

In [ ]:
pd.DataFrame(model_LOGREG.predict_proba(X_test), columns=model_LOGREG.classes_).head(5)

In [ ]:
pd.DataFrame(model_LOGREG.predict_proba(X_test))

In [ ]:
predictions_LOGREG[7]

In [ ]:
# For decode test patterns (just create a copy before transformation)
# add probability by index
# eliminate surface and density (although they would be worth us for other calculations)

In [ ]:
df_from_xlsx_total.head(1)

In [ ]:
df_ratings_lab_ohe.head(1)

In [ ]:
######### Visual tests

In [ ]:
#del visual
#del visual_sample

In [ ]:
visual = pd.DataFrame(model_LOGREG.predict_proba(X_test), columns=model_LOGREG.classes_)
visual_sample = visual.sample(n=5000).reset_index(drop=True)

In [ ]:
df_ratings_lab_ohe["CLASIFICACION"].unique()

In [ ]:
# Categorical scatterplots:

In [ ]:
sb.catplot(data=visual_sample,kind="strip", orient="h"
          )

In [ ]:
# Categorical distribution plots:

In [ ]:
sb.catplot(data=visual_sample,kind="box", orient="h"
          )

In [ ]:
visual_sample["2.5"][7]

In [ ]:
visual_sample[7:8]

In [ ]:
visual_sample["2.5"][:]

In [ ]:
sb.catplot(data=visual_sample,kind="violin", orient="h"
          )

In [ ]:
sb.catplot(data=visual_sample,kind="boxen", orient="h"
          )

In [ ]:
# Categorical estimate plots:

In [ ]:
sb.catplot(data=visual_sample,kind="point", orient="h"
          )

In [ ]:
sb.catplot(data=visual_sample,kind="bar", orient="h"
          )

In [ ]:
X_test.shape

In [ ]:
visual_sample.columns

In [ ]:
###################################

In [ ]:
!date

# Partial Dependence Plot

In [ ]:
from pdpbox import pdp

In [ ]:
pdp_goals = pdp.pdp_isolate(model=clf, dataset=X_test, model_features=X.columns, feature='Glucose')
pdp.pdp_plot(pdp_goals, 'Feature')
plt.show()

In [ ]:
!date